spring.application.name=first_project
server.port=8080

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/db_mini_crudapi}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:123456}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
